baseURL = 'https://carlosgustavoruiz.me/'
languageCode = 'en-us'
title = 'Carlos Gustavo Ruiz'
paginate = 12
publishDir = "docs"
theme = "PaperMod"
defaultTheme = "light"

[minify]
disableXML = true
minifyOutput = true

[params]
description = "technical curiosities log and random thoughts"

    [params.homeInfoParams]
    title = "Hi there!"
    Content = "some text"


    [params.profileMode]
    enabled = true
    subtitle = "Systems Engineer"
    imageUrl = "https://avatars.githubusercontent.com/u/1821644?v=4"
    imageWidth = 240
    imageHeight = 240


    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/carlosgruiz-dev"

    [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/carlosgruiz-dev"

    [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/carlosgruiz_dev"

    [[params.socialIcons]]
    name = "telegram"
    url = "https://t.me/carlosgruiz_dev"


[[menu.main]]
identifier = "blog"
name = "blog"
url = "/blog/"
weight = 30

[[menu.main]]
identifier = "wiki"
name = "wiki"
url = "https://github.com/carlosgruiz-dev/carlosgruiz-dev/wiki"
weight = 40

[[menu.main]]
identifier = "talks"
name = "talks"
url = "/talks/"
weight = 50

[[menu.main]]
identifier = "bookmarks"
name = "bookmarks"
url = "/bookmarks/"
weight = 60

[[menu.main]]
identifier = "now"
name = "now"
url = "/now/"
weight = 70
